/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.CrearMascota;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import Controlador.Modificar;
 
public class Menu extends javax.swing.JPanel {
    private Contenedor contenedor;
    
    DefaultTableModel tabla;
    int filas;
    
    public Menu(Contenedor contenedor) {
        
        this.contenedor = contenedor;
        initComponents();
        tabla = (DefaultTableModel) tablaMascota.getModel();
        
        tabla = new DefaultTableModel();
        tabla.addColumn("NOMBRE");
        tabla.addColumn("RAZA");
        tabla.addColumn("EDAD");
        tabla.addColumn("DUEÑO");
        tabla.addColumn("CELULAR");
        this.tablaMascota.setModel(tabla);
       
    }
     public void limpiar(){
        nombreMascota.setText("");
        razaMascota.setText("");
        edadMascota.setText("");
        nombreDuenno.setText("");
        celularDuenno.setText("");
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMascota = new javax.swing.JTable();
        nombreMascota = new javax.swing.JTextField();
        razaMascota = new javax.swing.JTextField();
        edadMascota = new javax.swing.JTextField();
        nombreDuenno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        celularDuenno = new javax.swing.JTextField();
        BotonCrear = new javax.swing.JButton();
        BotonModificar = new javax.swing.JButton();
        BotonEleiminar = new javax.swing.JButton();
        botonAtras = new javax.swing.JButton();

        jTextField6.setText("jTextField6");

        setMinimumSize(new java.awt.Dimension(550, 470));
        setPreferredSize(new java.awt.Dimension(550, 470));

        tablaMascota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaMascota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMascotaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaMascota);

        nombreMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreMascotaActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        jLabel3.setText("Raza");

        jLabel4.setText("Edad");

        jLabel5.setText("Nombre del dueño");

        jLabel6.setText("Celular");

        BotonCrear.setText("Crear");
        BotonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCrearActionPerformed(evt);
            }
        });

        BotonModificar.setText("Modificar");
        BotonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarActionPerformed(evt);
            }
        });

        BotonEleiminar.setText("Eliminar");
        BotonEleiminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEleiminarActionPerformed(evt);
            }
        });

        botonAtras.setText("Atras");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(razaMascota)
                                    .addComponent(edadMascota)
                                    .addComponent(nombreDuenno, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                                .addGap(87, 87, 87)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BotonModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BotonEleiminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(nombreMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                                .addComponent(BotonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(celularDuenno, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(129, 129, 129)
                                .addComponent(botonAtras)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonCrear)
                    .addComponent(nombreMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonModificar)
                    .addComponent(razaMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(BotonEleiminar))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edadMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(nombreDuenno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(celularDuenno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(60, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonAtras)
                        .addGap(42, 42, 42))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombreMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreMascotaActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        llevarAPrincipal();
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void BotonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCrearActionPerformed
        // TODO add your handling code here:
        String nombre = nombreMascota.getText();
        String raza = razaMascota.getText();
        String edad = edadMascota.getText();
        String duenno = nombreDuenno.getText();
        String celular = celularDuenno.getText();
        
        CrearMascota crearMascota = new CrearMascota();
        String[] annadirTabla = crearMascota.Crear(nombre, raza, edad, duenno, celular);
      
        tabla.addRow(annadirTabla);
        limpiar();
    }//GEN-LAST:event_BotonCrearActionPerformed

    private void tablaMascotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMascotaMouseClicked
      int seleccion = tablaMascota.getSelectedRow();
        
        nombreMascota.setText(tablaMascota.getValueAt(seleccion, 0).toString());
        razaMascota.setText(tablaMascota.getValueAt(seleccion, 1).toString());
        edadMascota.setText(tablaMascota.getValueAt(seleccion, 2).toString());
        nombreDuenno.setText(tablaMascota.getValueAt(seleccion, 3).toString());
        celularDuenno.setText(tablaMascota.getValueAt(seleccion, 4).toString());
        filas=seleccion;
    }//GEN-LAST:event_tablaMascotaMouseClicked

    private void BotonEleiminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEleiminarActionPerformed
        if (tablaMascota.getSelectedRow() != -1){
            tabla.removeRow(tablaMascota.getSelectedRow());
        }else {
            JOptionPane.showMessageDialog(null, "No has seleccionado un registro");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_BotonEleiminarActionPerformed

    private void BotonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarActionPerformed
        String nombre = nombreMascota.getText();
        String raza = razaMascota.getText();
        String edad = edadMascota.getText();
        String duenno = nombreDuenno.getText();
        String celular = celularDuenno.getText();
        
        Modificar modificar = new Modificar();
        String[] objectoTablaUsuario = modificar.modificar(nombre, raza, edad, duenno, celular);
        
        for (int i = 0; i < tablaMascota.getColumnCount(); i++) {
            tabla.setValueAt(objectoTablaUsuario [i], filas, i);
            
            limpiar();
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_BotonModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCrear;
    private javax.swing.JButton BotonEleiminar;
    private javax.swing.JButton BotonModificar;
    private javax.swing.JButton botonAtras;
    private javax.swing.JTextField celularDuenno;
    private javax.swing.JTextField edadMascota;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField nombreDuenno;
    private javax.swing.JTextField nombreMascota;
    private javax.swing.JTextField razaMascota;
    private javax.swing.JTable tablaMascota;
    // End of variables declaration//GEN-END:variables

private void llevarAPrincipal(){
    contenedor.regresar(this);
}


}
