
package vista;

import controlador.UsuarioCrear;
import modelo.Usuarios;
import javax.swing.JOptionPane;

public class CrearUsuarios extends javax.swing.JPanel {

    private final Principal principal;
    
    UsuarioCrear creacion_de_usuario = new UsuarioCrear();

    public CrearUsuarios(Principal principal) {
        this.principal = principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelar = new javax.swing.JToggleButton();
        añadir_usuario = new javax.swing.JToggleButton();
        contraseña_ingresar = new javax.swing.JTextField();
        contraseña = new javax.swing.JLabel();
        usuario_ingresar = new javax.swing.JTextField();
        usuario = new javax.swing.JLabel();
        telefono_ingresar = new javax.swing.JTextField();
        telefono = new javax.swing.JLabel();
        cargo_ingresar = new javax.swing.JTextField();
        cargo = new javax.swing.JLabel();
        cedula_ingresar = new javax.swing.JTextField();
        cedula = new javax.swing.JLabel();
        correo_ingresar = new javax.swing.JTextField();
        correo = new javax.swing.JLabel();
        nombre_ingresar = new javax.swing.JTextField();
        nombre = new javax.swing.JLabel();
        crearusuarios = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        LSE = new javax.swing.JLabel();
        salir = new javax.swing.JLabel();
        Icono_StarM1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancelar.setBackground(new java.awt.Color(204, 255, 255));
        cancelar.setFont(new java.awt.Font("Gadugi", 1, 30)); // NOI18N
        cancelar.setText("CANCELAR Y SALIR");
        cancelar.setToolTipText("salir de la creacion de usuarios");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 380, -1, -1));

        añadir_usuario.setBackground(new java.awt.Color(204, 255, 255));
        añadir_usuario.setFont(new java.awt.Font("Gadugi", 1, 30)); // NOI18N
        añadir_usuario.setText("AÑADIR USUARIO");
        añadir_usuario.setToolTipText("va a ingresar a un usuario");
        añadir_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadir_usuarioActionPerformed(evt);
            }
        });
        add(añadir_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, -1, -1));

        contraseña_ingresar.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        add(contraseña_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, 250, 35));

        contraseña.setFont(new java.awt.Font("Gadugi", 1, 30)); // NOI18N
        contraseña.setForeground(new java.awt.Color(0, 0, 0));
        contraseña.setText("Contraseña:");
        add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 530, -1, -1));

        usuario_ingresar.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        add(usuario_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 250, 35));

        usuario.setFont(new java.awt.Font("Gadugi", 1, 30)); // NOI18N
        usuario.setForeground(new java.awt.Color(0, 0, 0));
        usuario.setText("Usuario:");
        add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 480, -1, -1));

        telefono_ingresar.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        add(telefono_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 250, 35));

        telefono.setFont(new java.awt.Font("Gadugi", 1, 30)); // NOI18N
        telefono.setForeground(new java.awt.Color(0, 0, 0));
        telefono.setText("Telefono:");
        add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, -1, -1));

        cargo_ingresar.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        add(cargo_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 250, 35));

        cargo.setFont(new java.awt.Font("Gadugi", 1, 30)); // NOI18N
        cargo.setForeground(new java.awt.Color(0, 0, 0));
        cargo.setText("Cargo:");
        add(cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, -1));

        cedula_ingresar.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        add(cedula_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 250, 35));

        cedula.setFont(new java.awt.Font("Gadugi", 1, 30)); // NOI18N
        cedula.setForeground(new java.awt.Color(0, 0, 0));
        cedula.setText("Cedula:");
        add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, -1));

        correo_ingresar.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        add(correo_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 250, 35));

        correo.setFont(new java.awt.Font("Gadugi", 1, 30)); // NOI18N
        correo.setForeground(new java.awt.Color(0, 0, 0));
        correo.setText("Correo:");
        add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 280, -1, -1));

        nombre_ingresar.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        add(nombre_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 250, 35));

        nombre.setFont(new java.awt.Font("Gadugi", 1, 30)); // NOI18N
        nombre.setForeground(new java.awt.Color(0, 0, 0));
        nombre.setText("Nombres:");
        add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        crearusuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Iconos/CrearUsuarios.png"))); // NOI18N
        add(crearusuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jToggleButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jToggleButton1.setText("VOLVER");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 10, -1, -1));

        LSE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Imagenes/LSE.png"))); // NOI18N
        add(LSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Iconos/Salir.png"))); // NOI18N
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });
        add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 640, -1, -1));

        Icono_StarM1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Iconos/Logopequeño.png"))); // NOI18N
        add(Icono_StarM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 110, 150));

        fondo.setBackground(new java.awt.Color(204, 255, 255));
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Imagenes/Fondo2.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        // TODO add your handling code here:
        regresar();
    }//GEN-LAST:event_salirMouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        regresarausuarios();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void añadir_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadir_usuarioActionPerformed
        String name = nombre_ingresar.getText();
        String email = correo_ingresar.getText();
        String cc = cedula_ingresar.getText();
        String position = cargo_ingresar.getText();
        String cell = telefono_ingresar.getText();
        String user = usuario_ingresar.getText();
        String pass = contraseña_ingresar.getText();
       
        
        crear_usuario(name, email, cc, position, cell, user, pass);
        
    }//GEN-LAST:event_añadir_usuarioActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        regresarausuarios();
    }//GEN-LAST:event_cancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icono_StarM1;
    private javax.swing.JLabel LSE;
    private javax.swing.JToggleButton añadir_usuario;
    private javax.swing.JToggleButton cancelar;
    private javax.swing.JLabel cargo;
    private javax.swing.JTextField cargo_ingresar;
    private javax.swing.JLabel cedula;
    private javax.swing.JTextField cedula_ingresar;
    private javax.swing.JLabel contraseña;
    private javax.swing.JTextField contraseña_ingresar;
    private javax.swing.JLabel correo;
    private javax.swing.JTextField correo_ingresar;
    private javax.swing.JLabel crearusuarios;
    private javax.swing.JLabel fondo;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField nombre_ingresar;
    private javax.swing.JLabel salir;
    private javax.swing.JLabel telefono;
    private javax.swing.JTextField telefono_ingresar;
    private javax.swing.JLabel usuario;
    private javax.swing.JTextField usuario_ingresar;
    // End of variables declaration//GEN-END:variables

    
    private void crear_usuario (String name, String email, String cc, String position, String cell, String user, String pass) {
        if (user.equals("") || pass.equals("")) {

            JOptionPane.showMessageDialog(null, "no puede dejar campos vacios");
        } else {
            Usuarios datos = creacion_de_usuario.crear_usuario(name, email, cc, position, cell, user, pass);
            if (datos == null){
                JOptionPane.showMessageDialog(null ,"Creacion de Usuarios Exitosa " + user);
            }
        }
    }
    
    private void regresar(){
        principal.irAInicio(this);
    }
    
    private void regresarausuarios(){
        principal.irAUsuarios(this);
    }
}

