/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JPanel;

public class Contenedor extends javax.swing.JFrame {

      private Principal principal;
      private Login login;
      private Usuario usuario;
      private CrearUsuario crearusuario;
      private Inventario inventario;
      private Ingreso ingreso;
      private ModificarUsuario modificarusuario;
    /**
     * Creates new form Contenedor
     */
    public Contenedor() {
        setDefaultCloseOperation(EXIT_ON_CLOSE);// bootn cerrar
        setName("TIM");
        setTitle("TIM");
        setResizable(false);
        pack(); //trar todos los subcomponentes
        setIconImage(getIconImage());
        setLocationRelativeTo(null);//mirat
        login(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contenedor().setVisible(true);
            }
        });
    }

    
    public void login(){
        login = new Login(this);
        login.setVisible(true);
        add(login);
        pack();
        setLocationRelativeTo(null);
    }
    
    public void irAPrincipal (JPanel jPanel) {
        
        remove(jPanel);
        principal = new Principal(this);
        principal.setVisible(true);
        add(principal);
        pack();
        setLocationRelativeTo(null);  
    }
    
    public void irAUsuario (JPanel jPanel) {
        remove(jPanel);
        usuario = new Usuario(this);
        usuario.setVisible(true);
        add(usuario);
        pack();
        setLocationRelativeTo(null);
        
    }
    
    public void irALogin (JPanel jPanel){
        remove(jPanel);
        login = new Login(this);
        login.setVisible(true);
        add(login);
        pack();
        setLocationRelativeTo(null);
    }
    
    public void irACrearUsuario(JPanel jPanel){
        remove(jPanel);
        crearusuario = new CrearUsuario(this);
        crearusuario.setVisible(true);
        add(crearusuario);
        pack();
        setLocationRelativeTo(null);
        
    }
    
    public void irAInventario(JPanel jPanel){
        remove(jPanel);
        inventario = new Inventario(this);
        inventario.setVisible(true);
        add(inventario);
        pack();
        setLocationRelativeTo(null);
    }
    
    public void irAIngreso(JPanel jPanel){
        remove(jPanel);
        ingreso = new Ingreso(this);
        ingreso.setVisible(true);
        add(ingreso);
        pack();
        setLocationRelativeTo(null);
    }
    
    public void irAModificarUsuario (JPanel jPanel){
        remove(jPanel);
        modificarusuario = new ModificarUsuario (this);
        modificarusuario.setVisible(true);
        add(modificarusuario);
        pack();
        setLocationRelativeTo(null);
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
