/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JPanel;

/**
 *
 * @author eduardo Santamaria
 */
public class Principal extends javax.swing.JFrame {

    //RElLACIONES
     private InicioJPanel inicioJPanel;
     private Home home;
     //private Formulario formulario;
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        //initComponents();
        setDefaultCloseOperation(EXIT_ON_CLOSE);// bootn cerrar
        setName("pricipalJFrame");
        setTitle("Proyecto");
        setResizable(false);
        pack(); //trar todos los subcomponentes
        setIconImage(getIconImage());
        setLocationRelativeTo(null);//mirat
        iniciar();  
    }
    
public Image getIconImage() {
Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("recursos/icono_1.png"));
 return retValue;
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto\n");
        setName("principalJframe"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 104, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    //Me dice que va a pintar por primera vez en el jframe
    private void iniciar() {
        inicioJPanel = new InicioJPanel(this);
        inicioJPanel.setVisible(true);
        add(inicioJPanel);
        pack();
        setLocationRelativeTo(null);  
        
    }
    public void irAHome(JPanel jPanel) {
        remove(jPanel);
        home = new Home(this);
        home.setVisible(true);
        add(home);
        pack();
        setLocationRelativeTo(null);         
    }
    
    
      public  void irAInicioJPanel(JPanel jPanel) {        
        remove(jPanel);
        inicioJPanel = new InicioJPanel(this);
        inicioJPanel.setVisible(true);
        add(inicioJPanel);
        pack();
        setLocationRelativeTo(null); 
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
